### ISSUE TITLE
Issue with Replit for session string

### ISSUE THREAD

**Issue by yaya059** [aahnik/tg-login#3]
Hello 
i have the issue with the the package : https://replit.com/@aahnik/tg-login?v=1

when i forked and run on replit , i've got some issues and i have not the screen to enter API

if someone can help me please

thanks a lot 

Python 3.9.6
pip 21.1.3 from /nix/store/3xcbipxg7dacja7arkqsdp31wv48a59b-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip (python 3.9)
Requirement already satisfied: pip in /nix/store/3xcbipxg7dacja7arkqsdp31wv48a59b-python3.9-pip-21.1.3/lib/python3.9/site-packages (21.1.3)
Collecting pip
  Downloading pip-24.0-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 8.4 MB/s 
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.1.3
    Uninstalling pip-21.1.3:
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/nix/store/3xcbipxg7dacja7arkqsdp31wv48a59b-python3.9-pip-21.1.3/bin/pip'
Consider using the `--user` option or check the permissions.

WARNING: You are using pip version 21.1.3; however, version 24.0 is available.
You should consider upgrading via the '/nix/store/cgxc3jz7idrb1wnb2lard9rvcx6aw2si-python3-3.9.6/bin/python3.9 -m pip install --upgrade pip' command.
Error: [Errno 2] No such file or directory: '/home/runner/tg-login/.venv/bin/python'
Collecting tg-login
  Downloading tg_login-0.0.2-py3-none-any.whl (4.5 kB)
Collecting typer<0.4.0,>=0.3.2
  Downloading typer-0.3.2-py3-none-any.whl (21 kB)
Collecting Telethon<2.0.0,>=1.21.1
  Downloading Telethon-1.35.0.tar.gz (599 kB)
     |████████████████████████████████| 599 kB 11.2 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting python-dotenv<0.18.0,>=0.17.0
  Downloading python_dotenv-0.17.1-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: rsa in /nix/store/as3g1wmn9ra0r56fnm9lrf452am09jfq-python3.9-rsa-4.7.2/lib/python3.9/site-packages (from Telethon<2.0.0,>=1.21.1->tg-login) (4.7.2)
Collecting pyaes
  Downloading pyaes-1.6.1.tar.gz (28 kB)
    ERROR: Command errored out with exit status 1:
     command: /nix/store/cgxc3jz7idrb1wnb2lard9rvcx6aw2si-python3-3.9.6/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7tpnawuc/pyaes_5e2303a462f24e52a9bb34dc039636c4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7tpnawuc/pyaes_5e2303a462f24e52a9bb34dc039636c4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-sodb_svo
         cwd: /tmp/pip-install-7tpnawuc/pyaes_5e2303a462f24e52a9bb34dc039636c4/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/44/66/2c17bae31c906613795711fc78045c285048168919ace2220daa372c7d72/pyaes-1.6.1.tar.gz#sha256=02c1b1405c38d3c370b085fb952dd8bea3fadcee6411ad99f312cc129c536d8f (from https://pypi.org/simple/pyaes/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pyaes-1.6.0.tar.gz (28 kB)
    ERROR: Command errored out with exit status 1:
     command: /nix/store/cgxc3jz7idrb1wnb2lard9rvcx6aw2si-python3-3.9.6/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7tpnawuc/pyaes_fc8f8e04d6cf4d1faaefa6dc8c88b8f7/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7tpnawuc/pyaes_fc8f8e04d6cf4d1faaefa6dc8c88b8f7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-aew2gcqs
         cwd: /tmp/pip-install-7tpnawuc/pyaes_fc8f8e04d6cf4d1faaefa6dc8c88b8f7/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/63/31/6768a72cdca5dbd299ae798b690801e6c9c2f018332eec3c5fca79370dba/pyaes-1.6.0.tar.gz#sha256=9cd5a54d914b1eebfb14fcb490315214b6a0304d9f1bb47e90d1d8e0b15ce92e (from https://pypi.org/simple/pyaes/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pyaes-1.5.0.tar.gz (28 kB)
    ERROR: Command errored out with exit status 1:
     command: /nix/store/cgxc3jz7idrb1wnb2lard9rvcx6aw2si-python3-3.9.6/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7tpnawuc/pyaes_33e0d39b8f2a42e6b30d052dc95729e8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7tpnawuc/pyaes_33e0d39b8f2a42e6b30d052dc95729e8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rad_wblg
         cwd: /tmp/pip-install-7tpnawuc/pyaes_33e0d39b8f2a42e6b30d052dc95729e8/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/20/ab/645da9be4db12d6740ae551f2d2c7c570a5088bd34f74b283f7426c587a0/pyaes-1.5.0.tar.gz#sha256=da451f5dd01ae91907c9c081aeea6c9b81c75d869d41ff5d4f220fce08ed5b03 (from https://pypi.org/simple/pyaes/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pyaes-1.4.0.tar.gz (27 kB)
    ERROR: Command errored out with exit status 1:
     command: /nix/store/cgxc3jz7idrb1wnb2lard9rvcx6aw2si-python3-3.9.6/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7tpnawuc/pyaes_97074b6022a046e081f41922eae44ee2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7tpnawuc/pyaes_97074b6022a046e081f41922eae44ee2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-diejl37t
         cwd: /tmp/pip-install-7tpnawuc/pyaes_97074b6022a046e081f41922eae44ee2/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/22/52/4d3910757ec0ef3a8a105a3ba872977c6bc73f10aba9353ee6ffbae8b62a/pyaes-1.4.0.tar.gz#sha256=0507c918702af11e5dffec68850fd34645ab646b468b86be60a1f3cb4c33ec94 (from https://pypi.org/simple/pyaes/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pyaes-1.3.0.tar.gz (27 kB)
    ERROR: Command errored out with exit status 1:
     command: /nix/store/cgxc3jz7idrb1wnb2lard9rvcx6aw2si-python3-3.9.6/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7tpnawuc/pyaes_22ffb8be6f6b4c3e97650ae526dad26d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7tpnawuc/pyaes_22ffb8be6f6b4c3e97650ae526dad26d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8pao7ps1
         cwd: /tmp/pip-install-7tpnawuc/pyaes_22ffb8be6f6b4c3e97650ae526dad26d/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/5f/04/3d70937868f65d87100835afebecaffa0b010ae49dc2f67a39bee6da9606/pyaes-1.3.0.tar.gz#sha256=c2f2baf9316bbdaa1b44c8e57d347c97e8396470c644d606bb5c3489dc3a3384 (from https://pypi.org/simple/pyaes/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pyaes-1.2.0.tar.gz (26 kB)
    ERROR: Command errored out with exit status 1:
     command: /nix/store/cgxc3jz7idrb1wnb2lard9rvcx6aw2si-python3-3.9.6/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7tpnawuc/pyaes_5c3db89e32364afcbb18e9a5f9c1bc00/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7tpnawuc/pyaes_5c3db89e32364afcbb18e9a5f9c1bc00/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-s6_sucuv
         cwd: /tmp/pip-install-7tpnawuc/pyaes_5c3db89e32364afcbb18e9a5f9c1bc00/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/13/76/fd86c3137db9eba4dcfc26fc782e9d0231e57334abd35c9576db1d02de8f/pyaes-1.2.0.tar.gz#sha256=04360103d2c98767a844780beff7d37df33f4516cff48f95363779ba0cbc161a (from https://pypi.org/simple/pyaes/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pyaes-1.1.0.tar.gz (25 kB)
    ERROR: Command errored out with exit status 1:
     command: /nix/store/cgxc3jz7idrb1wnb2lard9rvcx6aw2si-python3-3.9.6/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7tpnawuc/pyaes_22e2d375341f4e79862bdff4d9cf1ed2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7tpnawuc/pyaes_22e2d375341f4e79862bdff4d9cf1ed2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-flnfi0pp
         cwd: /tmp/pip-install-7tpnawuc/pyaes_22e2d375341f4e79862bdff4d9cf1ed2/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bd/5f/4ad4a42ad3f2db769dca2d0fd533cc7279929844367b581ed0bdc3e39c3a/pyaes-1.1.0.tar.gz#sha256=7f282d13c2bed0a7f349173af86217213d2e39f9fd3831d3e981d9dee23c293d (from https://pypi.org/simple/pyaes/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pyaes-1.0.0.tar.gz (23 kB)
    ERROR: Command errored out with exit status 1:
     command: /nix/store/cgxc3jz7idrb1wnb2lard9rvcx6aw2si-python3-3.9.6/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7tpnawuc/pyaes_0b03ace460be4e0086e3aabf0db00c25/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7tpnawuc/pyaes_0b03ace460be4e0086e3aabf0db00c25/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mv20qrqr
         cwd: /tmp/pip-install-7tpnawuc/pyaes_0b03ace460be4e0086e3aabf0db00c25/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/08/c4/da99734108e159e5ca496736824c7ed5484b7aaa471341758d4be97ed014/pyaes-1.0.0.tar.gz#sha256=ad4ee0d7effde2ce1db0cbb82ca8b008123f0a892fc7292f60d529b747006a75 (from https://pypi.org/simple/pyaes/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pyaes-0.1.0.tar.gz (21 kB)
    ERROR: Command errored out with exit status 1:
     command: /nix/store/cgxc3jz7idrb1wnb2lard9rvcx6aw2si-python3-3.9.6/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7tpnawuc/pyaes_9ec6c0ac546f42bcb5540b9eed9ff6b0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7tpnawuc/pyaes_9ec6c0ac546f42bcb5540b9eed9ff6b0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ri4ubgd5
         cwd: /tmp/pip-install-7tpnawuc/pyaes_9ec6c0ac546f42bcb5540b9eed9ff6b0/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/59/af/cb8be1aa6e39d08888c68a9f256d482786adde98b6cbbe70c3b90056f38e/pyaes-0.1.0.tar.gz#sha256=65d6bb76a0c49d9bd2df27a9dd2c2223ae540ae253b4c459f0dbcb825d9420fe (from https://pypi.org/simple/pyaes/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Collecting Telethon<2.0.0,>=1.21.1
  Downloading Telethon-1.34.0.tar.gz (576 kB)
     |████████████████████████████████| 576 kB 39.8 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Downloading Telethon-1.33.1.tar.gz (568 kB)
     |████████████████████████████████| 568 kB 29.1 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Downloading Telethon-1.33.0.tar.gz (568 kB)
     |████████████████████████████████| 568 kB 51.0 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Downloading Telethon-1.32.1.tar.gz (563 kB)
     |████████████████████████████████| 563 kB 44.3 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Downloading Telethon-1.32.0.tar.gz (563 kB)
     |████████████████████████████████| 563 kB 33.4 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Downloading Telethon-1.31.1.tar.gz (555 kB)
     |████████████████████████████████| 555 kB 21.1 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Downloading Telethon-1.31.0.tar.gz (555 kB)
     |████████████████████████████████| 555 kB 28.5 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Downloading Telethon-1.30.3.tar.gz (552 kB)
     |████████████████████████████████| 552 kB 21.6 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Downloading Telethon-1.30.2.tar.gz (552 kB)
     |████████████████████████████████| 552 kB 32.6 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Downloading Telethon-1.30.0.tar.gz (552 kB)
     |████████████████████████████████| 552 kB 24.6 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Downloading Telethon-1.29.3.tar.gz (548 kB)
     |████████████████████████████████| 548 kB 24.0 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Downloading Telethon-1.29.2.tar.gz (548 kB)
     |████████████████████████████████| 548 kB 41.3 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Downloading Telethon-1.29.1.tar.gz (548 kB)
     |████████████████████████████████| 548 kB 29.9 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Downloading Telethon-1.29.0.tar.gz (548 kB)
     |████████████████████████████████| 548 kB 33.0 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Downloading Telethon-1.28.5-py3-none-any.whl (600 kB)
     |████████████████████████████████| 600 kB 34.2 MB/s 
  Downloading Telethon-1.28.2-py3-none-any.whl (600 kB)
     |████████████████████████████████| 600 kB 35.1 MB/s 
  Downloading Telethon-1.28.1-py3-none-any.whl (600 kB)
     |████████████████████████████████| 600 kB 20.1 MB/s 
  Downloading Telethon-1.28.0-py3-none-any.whl (600 kB)
     |████████████████████████████████| 600 kB 38.0 MB/s 
  Downloading Telethon-1.27.0-py3-none-any.whl (598 kB)
     |████████████████████████████████| 598 kB 44.3 MB/s 
  Downloading Telethon-1.26.1-py3-none-any.whl (585 kB)
     |████████████████████████████████| 585 kB 43.1 MB/s 
  Downloading Telethon-1.26.0-py3-none-any.whl (584 kB)
     |████████████████████████████████| 584 kB 38.5 MB/s 
  Downloading Telethon-1.25.4-py3-none-any.whl (569 kB)
     |████████████████████████████████| 569 kB 15.0 MB/s 
  Downloading Telethon-1.25.3-py3-none-any.whl (569 kB)
     |████████████████████████████████| 569 kB 47.0 MB/s 
  Downloading Telethon-1.25.2-py3-none-any.whl (569 kB)
     |████████████████████████████████| 569 kB 30.5 MB/s 
  Downloading Telethon-1.25.1-py3-none-any.whl (569 kB)
     |████████████████████████████████| 569 kB 48.2 MB/s 
  Downloading Telethon-1.25.0-py3-none-any.whl (567 kB)
     |████████████████████████████████| 567 kB 68.7 MB/s 
  Downloading Telethon-1.24.0-py3-none-any.whl (528 kB)
     |████████████████████████████████| 528 kB 30.9 MB/s 
  Downloading Telethon-1.23.0-py3-none-any.whl (522 kB)
     |████████████████████████████████| 522 kB 44.3 MB/s 
  Downloading Telethon-1.22.0-py3-none-any.whl (519 kB)
     |████████████████████████████████| 519 kB 26.2 MB/s 
  Downloading Telethon-1.21.1-py3-none-any.whl (515 kB)
     |████████████████████████████████| 515 kB 36.7 MB/s 
INFO: pip is looking at multiple versions of python-dotenv to determine which version is compatible with other requirements. This could take a while.
Collecting python-dotenv<0.18.0,>=0.17.0
  Downloading python_dotenv-0.17.0-py2.py3-none-any.whl (18 kB)
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of tg-login to determine which version is compatible with other requirements. This could take a while.
Collecting tg-login
  Downloading tg_login-0.0.1.post1-py3-none-any.whl (4.1 kB)
  Downloading tg_login-0.0.1-py3-none-any.whl (4.0 kB)
setup complete
main.sh: line 9: tg-login: command not found

**Comment by willbetter2022** [comment]
same
